"""initial api tables

Revision ID: e11fa87de908
Revises: 
Create Date: 2026-06-06 22:38:46.583492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e11fa87de908'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('preferred_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('post_reactions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reactions_post_id'), ['post_id'], unique=False)

    op.create_table('test_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('subtopic_id', sa.String(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_attempts_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_subtopic_id'), ['subtopic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('user_interests',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    op.create_table('user_post_views',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('user_post_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_post_views_post_id'), ['post_id'], unique=False)

    op.create_table('user_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prompts_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prompts_user_id'), ['user_id'], unique=False)

    op.create_table('user_topic_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('cursor_module', sa.Integer(), nullable=False),
    sa.Column('cursor_subtopic', sa.Integer(), nullable=False),
    sa.Column('cursor_seq', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_topic_progress')
    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prompts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_prompts_topic_id'))

    op.drop_table('user_prompts')
    with op.batch_alter_table('user_post_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_post_views_post_id'))

    op.drop_table('user_post_views')
    op.drop_table('user_interests')
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_attempts_subtopic_id'))
        batch_op.drop_index(batch_op.f('ix_test_attempts_post_id'))

    op.drop_table('test_attempts')
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reactions_post_id'))

    op.drop_table('post_reactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
